/* Generated by startup_generator */

#include <stm32f10x.h>
#include <stm32f10x_conf.h>
#include <core_cm3.h>


void __attribute__((weak)) __libc_init_array(void) {}

// Linker supplied pointers

extern unsigned long _sidata;
extern unsigned long _sdata;
extern unsigned long _edata;
extern unsigned long _sbss;
extern unsigned long _ebss;

extern int main(void);


void Reset_Handler(void) __attribute__((__interrupt__));
void Reset_Handler(void)
{

    unsigned long *src, *dst;

    src = &_sidata;
    dst = &_sdata;

    // Copy data initializers

    while (dst < &_edata)
    { *(dst++) = *(src++); }

    // Zero bss

    dst = &_sbss;
    while (dst < &_ebss)
    { *(dst++) = 0; }

    SystemInit();
    __libc_init_array();
    main();
    while (1) {}
}

void default_handler(void) __attribute__((__interrupt__));
void default_handler(void)
{
    assert_failed((uint8_t*)"startup_stm32f10x.c", __LINE__);
    while (1);
}

/* Vector Table */

void __attribute__((weak)) NMI_Handler(void);
void __attribute__((weak)) HardFault_Handler(void);
void __attribute__((weak)) MemManage_Handler(void);
void __attribute__((weak)) BusFault_Handler(void);
void __attribute__((weak)) UsageFault_Handler(void);
void __attribute__((weak)) SVC_Handler(void);
void __attribute__((weak)) DebugMon_Handler(void);
void __attribute__((weak)) PendSV_Handler(void);
void __attribute__((weak)) SysTick_Handler(void);
void __attribute__((weak)) WWDG_IRQHandler(void);
void __attribute__((weak)) PVD_IRQHandler(void);
void __attribute__((weak)) TAMPER_IRQHandler(void);
void __attribute__((weak)) RTC_IRQHandler(void);
void __attribute__((weak)) FLASH_IRQHandler(void);
void __attribute__((weak)) RCC_IRQHandler(void);
void __attribute__((weak)) EXTI0_IRQHandler(void);
void __attribute__((weak)) EXTI1_IRQHandler(void);
void __attribute__((weak)) EXTI2_IRQHandler(void);
void __attribute__((weak)) EXTI3_IRQHandler(void);
void __attribute__((weak)) EXTI4_IRQHandler(void);
void __attribute__((weak)) DMA1_Channel1_IRQHandler(void);
void __attribute__((weak)) DMA1_Channel2_IRQHandler(void);
void __attribute__((weak)) DMA1_Channel3_IRQHandler(void);
void __attribute__((weak)) DMA1_Channel4_IRQHandler(void);
void __attribute__((weak)) DMA1_Channel5_IRQHandler(void);
void __attribute__((weak)) DMA1_Channel6_IRQHandler(void);
void __attribute__((weak)) DMA1_Channel7_IRQHandler(void);
void __attribute__((weak)) ADC1_IRQHandler(void);
void __attribute__((weak)) EXTI9_5_IRQHandler(void);
void __attribute__((weak)) TIM1_BRK_TIM15_IRQHandler(void);
void __attribute__((weak)) TIM1_UP_TIM16_IRQHandler(void);
void __attribute__((weak)) TIM1_TRG_COM_TIM17_IRQHandler(void);
void __attribute__((weak)) TIM1_CC_IRQHandler(void);
void __attribute__((weak)) TIM2_IRQHandler(void);
void __attribute__((weak)) TIM3_IRQHandler(void);
void __attribute__((weak)) TIM4_IRQHandler(void);
void __attribute__((weak)) I2C1_EV_IRQHandler(void);
void __attribute__((weak)) I2C1_ER_IRQHandler(void);
void __attribute__((weak)) I2C2_EV_IRQHandler(void);
void __attribute__((weak)) I2C2_ER_IRQHandler(void);
void __attribute__((weak)) SPI1_IRQHandler(void);
void __attribute__((weak)) SPI2_IRQHandler(void);
void __attribute__((weak)) USART1_IRQHandler(void);
void __attribute__((weak)) USART2_IRQHandler(void);
void __attribute__((weak)) USART3_IRQHandler(void);
void __attribute__((weak)) EXTI15_10_IRQHandler(void);
void __attribute__((weak)) RTCAlarm_IRQHandler(void);
void __attribute__((weak)) CEC_IRQHandler(void);
void __attribute__((weak)) TIM6_DAC_IRQHandler(void);
void __attribute__((weak)) TIM7_IRQHandler(void);

/* weak aliases for each Exception handler to the default_handler.
 * Any function with the same name will override these definitions.
 */
#pragma weak NMI_Handler                   = default_handler
#pragma weak HardFault_Handler             = default_handler
#pragma weak MemManage_Handler             = default_handler
#pragma weak BusFault_Handler              = default_handler
#pragma weak UsageFault_Handler            = default_handler
#pragma weak SVC_Handler                   = default_handler
#pragma weak DebugMon_Handler              = default_handler
#pragma weak PendSV_Handler                = default_handler
#pragma weak SysTick_Handler               = default_handler
#pragma weak WWDG_IRQHandler               = default_handler
#pragma weak PVD_IRQHandler                = default_handler
#pragma weak TAMPER_IRQHandler             = default_handler
#pragma weak RTC_IRQHandler                = default_handler
#pragma weak FLASH_IRQHandler              = default_handler
#pragma weak RCC_IRQHandler                = default_handler
#pragma weak EXTI0_IRQHandler              = default_handler
#pragma weak EXTI1_IRQHandler              = default_handler
#pragma weak EXTI2_IRQHandler              = default_handler
#pragma weak EXTI3_IRQHandler              = default_handler
#pragma weak EXTI4_IRQHandler              = default_handler
#pragma weak DMA1_Channel1_IRQHandler      = default_handler
#pragma weak DMA1_Channel2_IRQHandler      = default_handler
#pragma weak DMA1_Channel3_IRQHandler      = default_handler
#pragma weak DMA1_Channel4_IRQHandler      = default_handler
#pragma weak DMA1_Channel5_IRQHandler      = default_handler
#pragma weak DMA1_Channel6_IRQHandler      = default_handler
#pragma weak DMA1_Channel7_IRQHandler      = default_handler
#pragma weak ADC1_IRQHandler               = default_handler
#pragma weak EXTI9_5_IRQHandler            = default_handler
#pragma weak TIM1_BRK_TIM15_IRQHandler     = default_handler
#pragma weak TIM1_UP_TIM16_IRQHandler      = default_handler
#pragma weak TIM1_TRG_COM_TIM17_IRQHandler = default_handler
#pragma weak TIM1_CC_IRQHandler            = default_handler
#pragma weak TIM2_IRQHandler               = default_handler
#pragma weak TIM3_IRQHandler               = default_handler
#pragma weak TIM4_IRQHandler               = default_handler
#pragma weak I2C1_EV_IRQHandler            = default_handler
#pragma weak I2C1_ER_IRQHandler            = default_handler
#pragma weak I2C2_EV_IRQHandler            = default_handler
#pragma weak I2C2_ER_IRQHandler            = default_handler
#pragma weak SPI1_IRQHandler               = default_handler
#pragma weak SPI2_IRQHandler               = default_handler
#pragma weak USART1_IRQHandler             = default_handler
#pragma weak USART2_IRQHandler             = default_handler
#pragma weak USART3_IRQHandler             = default_handler
#pragma weak EXTI15_10_IRQHandler          = default_handler
#pragma weak RTCAlarm_IRQHandler           = default_handler
#pragma weak CEC_IRQHandler                = default_handler
#pragma weak TIM6_DAC_IRQHandler           = default_handler
#pragma weak TIM7_IRQHandler               = default_handler

 /* exception and interrupt vector table ------------------------------------*/
typedef void (*ExceptionHandler)(void);
typedef union {
    ExceptionHandler handler;
    void             *pointer;
} VectorTableEntry;

extern unsigned _estack;

__attribute__((section(".isr_vector")))

VectorTableEntry const g_pfnVectors[] =
{
    { .pointer = &_estack                      },
    { .handler = &Reset_Handler                },    /* Reset Handler */
    { .handler = &default_handler },    /* NMI Handler */
    { .handler = &default_handler },    /* Hard Fault Handler */
    { .handler = &default_handler },    /* MPU Fault Handler */
    { .handler = &default_handler },    /* Bus Fault Handler */
    { .handler = &default_handler },    /* Usage Fault Handler */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* SVCall Handler */
    { .handler = &default_handler },    /* Debug Monitor Handler */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* PendSV Handler */
    { .handler = &default_handler },    /* SysTick Handler */
    { .handler = &default_handler },    /* Window Watchdog */
    { .handler = &default_handler },    /* PVD through EXTI Line detect */
    { .handler = &default_handler },    /* Tamper */
    { .handler = &default_handler },    /* RTC */
    { .handler = &default_handler },    /* Flash */
    { .handler = &default_handler },    /* RCC */
    { .handler = &default_handler },    /* EXTI Line 0 */
    { .handler = &default_handler },    /* EXTI Line 1 */
    { .handler = &default_handler },    /* EXTI Line 2 */
    { .handler = &default_handler },    /* EXTI Line 3 */
    { .handler = &default_handler },    /* EXTI Line 4 */
    { .handler = &default_handler },    /* DMA1 Channel 1 */
    { .handler = &default_handler },    /* DMA1 Channel 2 */
    { .handler = &default_handler },    /* DMA1 Channel 3 */
    { .handler = &default_handler },    /* DMA1 Channel 4 */
    { .handler = &default_handler },    /* DMA1 Channel 5 */
    { .handler = &default_handler },    /* DMA1 Channel 6 */
    { .handler = &default_handler },    /* DMA1 Channel 7 */
    { .handler = &default_handler },    /* ADC1 */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* EXTI Line 9..5 */
    { .handler = &default_handler },    /* TIM1 Break and TIM15 */
    { .handler = &default_handler },    /* TIM1 Update and TIM16 */
    { .handler = &default_handler },    /* TIM1 Trigger and Commutation and TIM17 */
    { .handler = &default_handler },    /* TIM1 Capture Compare */
    { .handler = &default_handler },    /* TIM2 */
    { .handler = &default_handler },    /* TIM3 */
    { .handler = &default_handler },    /* TIM4 */
    { .handler = &default_handler },    /* I2C1 Event */
    { .handler = &default_handler },    /* I2C1 Error */
    { .handler = &default_handler },    /* I2C2 Event */
    { .handler = &default_handler },    /* I2C2 Error */
    { .handler = &default_handler },    /* SPI1 */
    { .handler = &default_handler },    /* SPI2 */
    { .handler = &default_handler },    /* USART1 */
    { .handler = &default_handler },    /* USART2 */
    { .handler = &default_handler },    /* USART3 */
    { .handler = &default_handler },    /* EXTI Line 15..10 */
    { .handler = &default_handler },    /* RTC Alarm through EXTI Line */
    { .handler = &default_handler },    /* HDMI-CEC */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* Reserved */
    { .handler = &default_handler },    /* TIM6 and DAC underrun */
    { .handler = &default_handler },    /* TIM7 */
};

